server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: gateway-service
cloud:
  gateway:
    routes:
      - id: goods-service
        uri: http://localhost:8081/
        predicates:
          - Path=/api/goods/**
      - id: feedback-service
        uri: http://localhost:8083/
        predicates:
          - Path=/api/feedback/**
      - id: basket-service
        uri: http://localhost:8082/
        predicates:
          - Path=/api/baskets/**